jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ["g++-8", "g++-11"]
    steps:
      - uses: actions/checkout@v3
      - name: Install compiler
        run: sudo apt-get update && sudo apt-get install -y g++-${{ matrix.compiler }}
      - name: Compile
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}
    env:
      COMPILER: ${{ matrix.compiler }} # Optional: set a custom env variable
